name: JIT_Access
description: Policy for admin JIT for repos in this org

resource: repository

configuration:
  jitAccess:
    enabled: true
    maxHours: 2
    approvers:
    requestors:
      role: write
      users:
