name: run mgdp in pipeline test

on:
  workflow_dispatch:

jobs:
  runMgdp:
    runs-on: windows-latest

    steps:
    - name: Perform a Pester test from the Tests.ps1 file
      shell: pwsh
      run: Write-Output "test"
