
name: run mgdp in pipeline test

on:
  workflow_dispatch:

jobs:
  runMgdp:
    runs-on: windows-latest

    steps:
    - name: Perform a Pester test from the Tests.ps1 file
      shell: pwsh
      run: |
        $url = "https://github.com/microsoftgraph/msgraph-developer-proxy/releases/download/v0.6.0/msgraph-developer-proxy-win-x64-v0.6.0.zip"
        $dest = ".\mgdp"
        Invoke-WebRequest -Uri $url -OutFile "$dest.zip"
        Expand-Archive "$dest.zip" -DestinationPath $dest
        cd mgdp
        dir
        mgdp.exe

